### PR TITLE
Feat/support tag motification

### PR DESCRIPTION
**Pull request by Julian-Chu**
Issue: [[Elasticache] tags not modified](https://github.com/aws-controllers-k8s/community/issues/1738)

Description of changes:
- add creating status (add message and set ACK.ResourceSynced to false when replication group is being created)
```yaml
    - status: "False"
      type: ACK.ResourceSynced
      message:  "replication group currently being created."
```
- add syncTags and getTags
- now sdkFind updates ko.Spec.Tags(latest status)
- add E2E test case

some comments are copied from RDS controller

### CODE REVIEW

**Review by A-Hilaly — APPROVED** [review]
Clean! thank you @Julian-Chu !

non blocking nit: Not sure if we should keep `util.py` file, or just bring the changes of testing framework from https://github.com/aws-controllers-k8s/memorydb-controller/tree/main/test/e2e/declarative_test_fwk . Maybe even doing everything using `test-infra/acktest` could be a good option.

**Comment by Julian-Chu** [comment]
> Clean! thank you @Julian-Chu !
> 
> non blocking nit: Not sure if we should keep `util.py` file, or just bring the changes of testing framework from https://github.com/aws-controllers-k8s/memorydb-controller/tree/main/test/e2e/declarative_test_fwk . Maybe even doing everything using `test-infra/acktest` could be a good option.

thanks @A-Hilaly ,  I am not professional in python, so need more time to investigate,  plan to create new PR to refactor later.   let's keep this PR small. 😄

**Review by A-Hilaly — APPROVED** [review]
Thank you Sir! 🙇  
/lgtm

**Pull request merged**
