### PR TITLE
tags and sync

### PR DESCRIPTION
**Pull request by kumargauravsharma**
Issue #, if available:

Description of changes:

This PR includes changes from @jaypipes in PR: https://github.com/aws-controllers-k8s/elasticache-controller/pull/56
And fixes the issue: https://github.com/aws-controllers-k8s/community/issues/950

when e2e tests pass, the https://github.com/aws-controllers-k8s/elasticache-controller/pull/56 can be merged first, and then this PR can be rebased and merged after that.
* e2e tests have passed

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jaypipes — APPROVED** [review]
:+1: thanks @kumargauravsharma!

**Comment by kumargauravsharma** [comment]
Merging this change as https://github.com/aws-controllers-k8s/elasticache-controller/pull/56 has been merged and this PR has been approved and e2e tests passed.

**Pull request merged**
