### PR TITLE
bring controller to runtime v0.20.1

### PR DESCRIPTION
**Pull request by jaypipes**
Brings ACK runtime v0.20.1 and aws-sdk-go v1.44.93 to Elasticache controller.

Needed to modify the `config/iam/KMS-policy-template.json` to include the
now-necessary CloudWatch Logs permissions that the testing framework uses.

Signed-off-by: Jay Pipes <jaypipes@gmail.com>

By submitting this pull request, I confirm that my contribution is made
under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by RedbackThomson** [comment]
I don't understand what this `KMS-policy-template.json` is? Is it because we need a mix of inline policies and recommended policy ARNs to install the permissions for the controller? Can we not just do it all within an inline policy?

**Comment by jaypipes** [comment]
> I don't understand what this `KMS-policy-template.json` is? Is it because we need a mix of inline policies and recommended policy ARNs to install the permissions for the controller? Can we not just do it all within an inline policy?

@RedbackThomson it is specifically for the e2e testing that this controller uses...

**Comment by A-Hilaly** [comment]
Ohhh i just saw this doc https://github.com/aws-controllers-k8s/elasticache-controller/blob/main/config/iam/README.md#kms-key-management-service

**Comment by A-Hilaly** [comment]
@kumargauravsharma The failing tests i pinged you about also appears in this PR. Checkout https://prow.ack.aws.dev/view/s3/ack-prow-logs/pr-logs/pull/aws-controllers-k8s_elasticache-controller/98/elasticache-recommended-policy-test/1583202603003547648

**Review by A-Hilaly — APPROVED** [review]
++
/lgtm

**Pull request merged**
