### PR TITLE
release artifacts for release v0.0.4

### PR DESCRIPTION
**Pull request by vijtrip2**
Description of changes:
Generating the latest helm chart templates for elasticache controller. This will help in running soak test and scraping metrics for this service controller.

P.S. there were no changes in controller files when running `make build-controller`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by A-Hilaly** [comment]
@vijtrip2 can you, please, update `go.mod` to use runtime `v0.2.1` ?

**Review by jaypipes — APPROVED** [review]
:+1: 

Note that the Elasticache controller RBAC will need the cluster-role-binding to include `Secrets` (see aws-controllers-k8s/community#745) but we can do that later.

**Review by kumargauravsharma — CHANGES_REQUESTED** [review]
We would like to have successful e2e test run validate for the latest controller code before a release.
Thus, I request not to merge this PR at present.

**Pull request closed without merging**
