### PR TITLE
Remove User, UserGroup custom resources

### PR DESCRIPTION
**Pull request by kumargauravsharma**
Issue #, if available:

Remove `User`, `UserGroup` custom resources

Description of changes:
* Specified `User`,`UserGroup` under `ignore.resource_names` list inside `generator.yaml`
* Removed `User`, `UserGroup` custom resources files from controller.
* Regenerated controller code with updated `generator.yaml` using `AWS_SDK_GO_VERSION=v1.35.5`

`make test` passed.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by kumargauravsharma** [comment]
Should the changes in this PR require major Semantic Version ("X") increment for next 'preview'/'latest' (not tagged as `-stable`) release?

**Comment by jaypipes** [comment]
> Should the changes in this PR require major Semantic Version ("X") increment for next 'preview'/'latest' (not tagged as `-stable`) release?

SemVer is the thing that indicates whether a change breaks API/interface compatibility, not the term "Preview" or "General Availability".

Also note the following from the SemVer document:

    Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

So, any release of a controller with a v0.y.z release tag is the signal to consumers that the public API may change in breaking ways up until a v1.y.z release tag.

**Comment by kumargauravsharma** [comment]
Thanks @jaypipes 
Please review the Files changed, and feel free to merge if changes are good.

**Review by jaypipes — APPROVED** [review]
:+1:

**Pull request merged**
