### PR TITLE
Add tags

### PR DESCRIPTION
**Pull request by rbranche**
Issue #, if available: aws-controllers-k8s/community#915

Description of changes: Update elasticache controller to include Tags in its API again.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by RedbackThomson** [comment]
Hey! Thanks for adding this back into the spec. This PR seems to contain changes to the tags as well as updates to the newest version of the code-generator and runtime. Either checkout the `v0.7.0` tag of `code-generator` and regenerate, or create a separate PR for upgrading to `v0.13.0`. This would just help us keep the scope of PRs down.

**Comment by rbranche** [comment]
@RedbackThomson. You're welcome. I have regenerated the code with code-generator v0.7.0, but I still had to update the test data to work properly and I'm still hitting the same test failure as mentioned here: https://github.com/aws-controllers-k8s/community/issues/915#issuecomment-908765952

**Comment by kumargauravsharma** [comment]
@rbranche Thank you.

The Tags from Spec were only applied during custom resource creation but Update tags, Remove tags scenarios were not working.
There is an open issue: Consistent Tags resource handling: https://github.com/aws-controllers-k8s/community/issues/63

Following ElastiCache APIs corresponds to List, Add, Update scenarios:
* https://docs.aws.amazon.com/cli/latest/reference/elasticache/list-tags-for-resource.html
* https://docs.aws.amazon.com/cli/latest/reference/elasticache/add-tags-to-resource.html
* https://docs.aws.amazon.com/cli/latest/reference/elasticache/remove-tags-from-resource.html
Reference ElastiCache controller issue related to use of these APIs for Tags: https://github.com/aws-controllers-k8s/community/issues/261

Thus, Tags field was removed from the Spec in favor of https://github.com/aws-controllers-k8s/community/issues/63

To add Tags to Spec, the service controller code needs to align with the solution from https://github.com/aws-controllers-k8s/community/issues/63 and invoke the service APIs mentioned above.

**Review by kumargauravsharma — CHANGES_REQUESTED** [review]
Changes required to aling with https://github.com/aws-controllers-k8s/community/issues/63
And to use of List, Update, Delete APIs for tags.

**Comment by rbranche** [comment]
It looks like I don't have the domain knowledge to complete this then.

**Pull request closed without merging**
